# Generated by Django 4.2.27 on 2025-12-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_phone_user_address_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='rent_amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('SELL', 'For Sale'), ('RENT', 'For Rent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('TENANT', 'Tenant'), ('AGENT', 'Agent')], max_length=10),
        ),
    ]
