# Generated by Django 5.2.8 on 2025-12-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_rent_amount_property_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20),
        ),
    ]
