# Generated by Django 5.2.8 on 2025-12-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
