# Generated by Django 6.0 on 2025-12-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_payment_amount_alter_payment_platform_cut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='seller_amount_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='seller_amount_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
