# Generated by Django 4.2.27 on 2025-12-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_seller_amount_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20),
        ),
    ]
