# Generated by Django 4.2.27 on 2026-01-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_sold_status'),
        ('core', '0010_remove_property_image_propertyimage'),
    ]

    operations = [
    ]
